version: "3.8"

services:
  server1:
    build: .
    command: python server.py
    environment:
      - SERVER_NAME=server1
    networks:
      anycast_net:
        aliases:
          - server   # Shared alias for Anycast simulation

  server2:
    build: .
    command: python server.py
    environment:
      - SERVER_NAME=server2
    networks:
      anycast_net:
        aliases:
          - server   

  server3:
    build: .
    command: python server.py
    environment:
      - SERVER_NAME=server3
    networks:
      anycast_net:
        aliases:
          - server  

  # Client: Connects to hostname "server" which Docker DNS resolves to one of the three server containers .
  client:
    build: .
    command: python client.py
    depends_on:
      - server1
      - server2
      - server3
    networks:
      - anycast_net

networks:
  anycast_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16   